# Generated by Django 4.2.7 on 2024-01-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0002_requisition_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='is_active',
        ),
    ]
