# Generated by Django 4.2.7 on 2024-01-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0003_remove_requisition_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered')], default='pending', max_length=10),
        ),
    ]
