# Generated by Django 4.2.7 on 2023-12-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_inventory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='delicacy',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
