# Generated by Django 4.2.7 on 2023-12-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delicacy_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delicacy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='arrival_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
