# Generated by Django 4.2.7 on 2023-12-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_expiry_date_item_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
