# Generated by Django 4.2.7 on 2024-01-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_delicacy_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delicacy',
            name='image_url',
        ),
    ]
