# Generated by Django 4.2.7 on 2024-01-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_delicacy_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delicacy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
