# Generated by Django 4.2.7 on 2024-01-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='stocked',
            field=models.BooleanField(default=False),
        ),
    ]
